"""add_applications_and_documents

Revision ID: 43b366493c02
Revises: d53da3a3aa0b
Create Date: 2026-05-06 23:30:43.967141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b366493c02'
down_revision: Union[str, None] = 'd53da3a3aa0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=False),
    sa.Column('college', sa.String(length=500), nullable=False),
    sa.Column('graduation_year', sa.String(length=10), nullable=False),
    sa.Column('percentage', sa.String(length=10), nullable=False),
    sa.Column('gate_score', sa.String(length=10), nullable=True),
    sa.Column('gate_rank', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'processing', 'verified', 'action_required', 'under_review', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('admin_remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('marksheet', 'gate_scorecard', 'degree_certificate', 'caste_certificate', 'ews_certificate', name='documenttype'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'verified', 'mismatch', 'reupload_requested', name='documentstatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('mismatch_details', sa.Text(), nullable=True),
    sa.Column('reupload_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    op.drop_table('applications')
    # ### end Alembic commands ###